// ===========================
//  clubs-data.js
//  Single source of truth for all club data
// ===========================

const CLUBS = [
  {
    id: 1,
    name: "Robotics Club",
    shortName: "ROBO",
    category: "Technical",
    tagline: "Build. Program. Compete.",
    description: "The Robotics Club is a hub for students passionate about designing, building, and programming robots. From beginner workshops to national-level competitions, we cover the full spectrum of robotics — mechanical design, embedded systems, computer vision, and AI-based control systems.",
    banner: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=900&auto=format&fit=crop&q=70",
    logo: "🤖",
    color: "#6d5efc",
    members: 87,
    founded: "2018",
    chairperson: { name: "Ravi Shankar", year: "4th Year, ECE", avatar: "RS" },
    viceChair:   { name: "Meena Pillai", year: "3rd Year, CSE", avatar: "MP" },
    facultyAdvisor: { name: "Dr. Suresh Kumar", dept: "Department of ECE", avatar: "SK" },
    joinStatus: false,
    upcomingEvents: [1],
    goals: ["Conduct monthly hands-on workshops", "Participate in national robotics competitions", "Build an autonomous campus delivery robot", "Mentor junior students in embedded systems"],
    meetSchedule: "Every Saturday, 10:00 AM — Lab 4, Block B",
    contact: "robotics@college.edu"
  },
  {
    id: 2,
    name: "IEEE Student Branch",
    shortName: "IEEE",
    category: "Technical",
    tagline: "Advancing Technology for Humanity.",
    description: "The IEEE Student Branch connects students with the global IEEE network of engineers and technologists. We organize technical talks, paper presentations, coding contests, and industry visits. Members get access to IEEE Xplore, certifications, and internship opportunities.",
    banner: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=900&auto=format&fit=crop&q=70",
    logo: "⚡",
    color: "#3b82f6",
    members: 142,
    founded: "2015",
    chairperson:    { name: "Ananya Krishnan", year: "4th Year, EEE", avatar: "AK" },
    viceChair:      { name: "Siddharth Nair",  year: "3rd Year, ECE", avatar: "SN" },
    facultyAdvisor: { name: "Dr. Priya Menon", dept: "Department of EEE", avatar: "PM" },
    joinStatus: true,
    upcomingEvents: [2],
    goals: ["Host IEEE-certified workshops and webinars", "Publish student research in IEEE journals", "Conduct inter-college technical symposium", "Connect students with IEEE industry professionals"],
    meetSchedule: "Every Wednesday, 4:00 PM — Seminar Hall 2",
    contact: "ieee@college.edu"
  },
  {
    id: 3,
    name: "FOSS Club",
    shortName: "FOSS",
    category: "Technical",
    tagline: "Free & Open Source for Everyone.",
    description: "The Free and Open Source Software Club promotes the use, development, and philosophy of open-source software. We contribute to real-world open source projects, organize hackathons, and run Linux install fests. If you love coding and believe in open knowledge, this is your tribe.",
    banner: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=900&auto=format&fit=crop&q=70",
    logo: "💻",
    color: "#10b981",
    members: 63,
    founded: "2019",
    chairperson:    { name: "Karthik Raj",    year: "3rd Year, CSE", avatar: "KR" },
    viceChair:      { name: "Divya Thomas",   year: "2nd Year, IT",  avatar: "DT" },
    facultyAdvisor: { name: "Mr. Arun Mohan", dept: "Department of CSE", avatar: "AM" },
    joinStatus: false,
    upcomingEvents: [5],
    goals: ["Contribute to 10+ open source projects per semester", "Organize Linux install fest for freshers", "Run weekly code review and pair programming sessions", "Build and maintain college open source tools"],
    meetSchedule: "Every Tuesday, 5:00 PM — Computer Lab 2, Block C",
    contact: "foss@college.edu"
  },
  {
    id: 4,
    name: "NSS Club",
    shortName: "NSS",
    category: "Social",
    tagline: "Not Me, But You.",
    description: "The National Service Scheme unit of our college is dedicated to community development and social service. We organize blood donation camps, tree planting drives, literacy programs in rural areas, and disaster relief activities. NSS instills a sense of social responsibility and leadership.",
    banner: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=900&auto=format&fit=crop&q=70",
    logo: "🤝",
    color: "#f59e0b",
    members: 210,
    founded: "2010",
    chairperson:    { name: "Lakshmi Nair",    year: "4th Year, CIVIL", avatar: "LN" },
    viceChair:      { name: "Arjun Varma",     year: "3rd Year, MECH",  avatar: "AV" },
    facultyAdvisor: { name: "Dr. Geetha Devi", dept: "Department of Humanities", avatar: "GD" },
    joinStatus: false,
    upcomingEvents: [],
    goals: ["Conduct quarterly blood donation camps", "Adopt and develop a nearby village", "Run adult literacy and digital awareness programs", "Organize annual social service week"],
    meetSchedule: "Every Friday, 3:00 PM — NSS Room, Admin Block",
    contact: "nss@college.edu"
  },
  {
    id: 5,
    name: "Space Club",
    shortName: "SPACE",
    category: "Science",
    tagline: "Reach for the Stars.",
    description: "The Space Club brings together astronomy enthusiasts, aspiring aerospace engineers, and science lovers. We conduct stargazing nights, telescope sessions, model rocket launches, and space trivia competitions. We also follow and discuss live space missions from ISRO, NASA, and SpaceX.",
    banner: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=900&auto=format&fit=crop&q=70",
    logo: "🚀",
    color: "#8b5cf6",
    members: 55,
    founded: "2021",
    chairperson:    { name: "Neil Mathew",       year: "3rd Year, ECE",   avatar: "NM" },
    viceChair:      { name: "Sneha Rajan",        year: "2nd Year, CSE",   avatar: "SR" },
    facultyAdvisor: { name: "Dr. Vikram Sarabhai", dept: "Department of Physics", avatar: "VS" },
    joinStatus: false,
    upcomingEvents: [],
    goals: ["Host monthly stargazing and telescope sessions", "Launch a student-built model rocket", "Screen and discuss all major ISRO & NASA missions", "Compete in inter-college space quiz competitions"],
    meetSchedule: "Every Thursday, 6:00 PM — Rooftop Observatory",
    contact: "space@college.edu"
  },
  {
    id: 6,
    name: "Photography Club",
    shortName: "PHOTO",
    category: "Creative",
    tagline: "See the World Differently.",
    description: "The Photography Club is for anyone who loves capturing moments — from smartphone snappers to DSLR enthusiasts. We run weekly photo walks, editing workshops, and an annual photo exhibition. Our members have been published in college magazines, newspapers, and online platforms.",
    banner: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=900&auto=format&fit=crop&q=70",
    logo: "📷",
    color: "#ec4899",
    members: 48,
    founded: "2017",
    chairperson:    { name: "Priya Suresh",    year: "3rd Year, CSE",  avatar: "PS" },
    viceChair:      { name: "Rahul Menon",     year: "2nd Year, ECE",  avatar: "RM" },
    facultyAdvisor: { name: "Ms. Anitha John", dept: "Department of Fine Arts", avatar: "AJ" },
    joinStatus: false,
    upcomingEvents: [6],
    goals: ["Conduct weekly photo walks on and off campus", "Run monthly editing workshops (Lightroom, Photoshop)", "Publish a student photography magazine each semester", "Organize annual inter-college photo competition"],
    meetSchedule: "Every Sunday, 7:00 AM — Main Gate",
    contact: "photo@college.edu"
  }
];